name: build

on:
  push:
    branches: [master, beta]
  pull_request:
    branches: [master, beta]

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  build_and_test:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        node-version: [20]

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci

      - run: npm run build

      - run: npm run lint

      - run: npm run test

  deploy_package:
    needs: build_and_test
    runs-on: ubuntu-24.04
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: npm ci

      #- name: debug deploy_package
      #  uses: actions/bin/debug@master

      - run: npx semantic-release@24
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
